image: "registry.michelada.io/michelada/dockerfiles/ci/rails:2.7"

services:
  - postgres

stages:
  - test
  - deployment

cache:
  paths:
    - vendor/ruby

variables:
  RAILS_ENV: "test"
  DB_HOST: postgres
  POSTGRES_PASSWORD: loquesea
  POSTGRES_USER: loquesea

before_script:
  - bundle config set clean 'true'
  - bundle config set path 'vendor'
  - bundle install

rubocop:
  stage: test
  script:
    - yarn install
    - bundle exec rubocop

test:
  stage: test
  script:
    - yarn install
    - bundle exec rake db:create db:schema:load
    - bundle exec rake test

deployment:
  stage: deployment
  script:
    - gem install dpl --pre
    - dpl heroku api --api_key $HEROKU_API_KEY --app $HEROKU_APP_NAME
    - --run CMD 'heroku run rails db:migrate'
  only:
    refs:
      - master
